### ISSUE TITLE
Compile failure with base-4.11 / inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [portnov/dates#1]
`dates-0.2.2.1` advertises being compatible with `base >=4 && < 5`, but this is falsifiable by e.g. `base-4.11.1.0` which results in the build failure below:

```
Build profile: -w ghc-8.4.3 -O1
In order, the following will be built (use -v for more details):
 - dates-0.2.2.1 (lib) (first run)
Configuring library for dates-0.2.2.1..
Preprocessing library for dates-0.2.2.1..
Building library for dates-0.2.2.1..
[1 of 4] Compiling Data.Dates.Internal ( Data/Dates/Internal.hs, /tmp/dates-0.2.2.1/dist-newstyle/build/x86_64-linux/ghc-8.4.3/dates-0.2.2.1/build/Data/Dates/Internal.o )
[2 of 4] Compiling Data.Dates.Types ( Data/Dates/Types.hs, /tmp/dates-0.2.2.1/dist-newstyle/build/x86_64-linux/ghc-8.4.3/dates-0.2.2.1/build/Data/Dates/Types.o )

Data/Dates/Types.hs:62:10: error:
    • No instance for (Semigroup DateTime)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid DateTime’
   |
62 | instance Monoid DateTime where
   |          ^^^^^^^^^^^^^^^
```

There's no immediate action required as I have (in my function as Hackage Trustee) already performed a metadata revision for you on Hackage, see http://hackage.haskell.org/package/dates-0.2.2.1/revisions/

In case you intend to add support for base-4.11 the information at https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid#RecommendedVariant may be useful.

If you have any questions, please don't hesitate to ask me!

**Comment by portnov** [comment]
Thanks for the information!
I think I fixed it, for me it compiles now both with lts-12.5 and lts-11.21. I uploaded dates-0.2.2.2 version.

**Comment by hvr** [comment]
@portnov Unfortunately, it's not enough to merely test with Stackage snapshots before uploading to Hackage. Btw, there's https://github.com/haskell-CI/haskell-ci if you want a TravisCI-based Haslell CI setup for GitHub.

The `dates-0.2.2.2` release you just made advertises support for `base >= 4 && 4.12`, however it is *not* compatible with `base-4.8` and older as the following build report shows:

![dates](https://user-images.githubusercontent.com/285533/44006139-75fb0c98-9e7f-11e8-966a-0a902f01d865.png)

I've already rectified the metadata accordingly, see https://hackage.haskell.org/package/dates-0.2.2.2/revisions/

Please ask if you have any questions!
